title: "Ujjwal Kanth"
description: '<p>Software Engineer (at) Unbxd</p><small>IR, Golang, Distributed Systems</small>'
theme: jekyll-theme-minimal
github:
  is_user_page: true
  is_project_page: false
