base_url = "https://uknth.me"
compile_sass = true
theme = "zerm"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "one-dark"
render_emoji = true 

[extra]
author = "Ujjwal Kanth"
theme_color = "orange"
show_author = false
show_categories = true
show_tags = true
center = true
logo_text = "> uknth.me"
read_more = "Read More"
main_menu = [
    {url = "/", name = "Home"},
    {url = "/categories", name = "Categories"},
    {url = "/tags", name = "Tags"},
    {url = "/about", name = "About"},
    {url = "/resume", name = "Resume"},
]


