baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ujjwal Kanth'
theme = "artemis"

summaryLength = 15
enableEmoji = true

[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
    pre = '<i class="fa fa-home"></i>'

[[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 10
    pre = '<i class="fa fa-note-sticky"></i>'

[[menus.main]]
    name = 'Resume'
    pageRef = '/resume'
    weight = 30
    pre = '<i class="fa fa-file"></i>'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'github'
    tabWidth = 4

[taxonomies]
  tag = 'tags'

[params]
title = 'Ujjwal Kanth'
subtitle = "Architect @Unbxd"
noteworthies = [
    "IR",
    "Distributed System",
    "System Design",
    "Go",
    "Pink Floyd",
    "Schecter Demon 6 🎸",
]

description = ""

email = "mail@uknth.me"

github = "uknth"
mastodon = "https://c.im/@uknth"
keywords = "blog, minimal, technical"
rss = false
