# Thanks a ton to github.com/orhun, this ci.yaml has been taken directly from his
# blog's github action.
# https://github.com/orhun/personal-blog/blob/main/.github/workflows/ci.yml
name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  link-checker:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Check the links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --max-concurrency 1 -v content/*.md
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  spelling-checker:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Check spelling mistakes
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
          path: content
          ignore_words_file: .codespellignore