# Thanks a ton to github.com/orhun, this deploy.yaml has been taken directly from his
# blog's github action, with some minor modification.
# https://github.com/orhun/personal-blog/blob/main/.github/workflows/deploy.yml
name: build and deploy zola

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
      
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}